Add `hidePanel` configuration flag
nagata-yoshiteru/pbm-ppm-pgm-viewer-for-vscode pull request #31
Opened 2022-11-30 01:29 UTC by jean-lourenco

This PR adds the `hidePanel` configuration flag that... well, hides the zoom/side panel entirely.
I have little use for the panel and it occupies a lot of the screen, it would be nice to have an option to disable it.

This is not the cleanest code, but I think it gets the job done.

2022-11-30 04:12 UTC, BenWeisz requested changes
Just a few things @jean-lourenco 
It looks like with these changes the feature works properly but I would appreciate a review @nagata-yoshiteru :)

2022-11-30 04:54 UTC, nagata-yoshiteru approved these changes
Thanks, @jean-lourenco and @BenWeisz !
I think it works properly now and approve these changes!

2022-11-30 04:55 UTC, nagata-yoshiteru approved these changes

2022-11-30 15:17 UTC, BenWeisz approved these changes
Looks good :)

2022-12-01 00:50 UTC, nagata-yoshiteru commented
Thanks, @jean-lourenco and @BenWeisz !
I will merge this PR and publish new version.

2022-12-01 00:50 UTC, merged